#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
# Format: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO
input="/etc/passwd"
while read -r line
do
	uname=$(cut -d ':' -f 1 <<< "$line")
	gid=$(cut -d ':' -f 4 <<< "$line")
	hdir=$(cut -d ':' -f 6 <<< "$line")
	cmd=$(cut -d ':' -f 7 <<< "$line")
	uid=$(cut -d ':' -f 3 <<< "$line")
	pswd=$(cut -d ':' -f 2 <<< "$line")
	uidi=$(cut -d ':' -f 5 <<< "$line")
	echo "The user $uname is part of the $gid gang, lives in $hdir and rides $cmd. $uid's place is protected by the passcode $pswd, more info about the user here: $uidi"
done < "$input"

