#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes: display hours from 0 to 12. display minutes from 1 to 59
hrs=0
while [ $hrs -le 12 ];do
	echo "Hour: "$hrs
	min=1
	while [	$min -le 59 ];do
		echo $min
		((min++))
	done
	((min=1))
	((hrs++))
done
